server:
  port: 9050
  
PETROLEUM_WELL_SUBSET: https://services5.arcgis.com/D9dI3nY76wGaru7T/arcgis/rest/services/PETROLEUM_WELL_subset/FeatureServer
TILE_DRAINAGE_AREA_SUBSET: https://services5.arcgis.com/D9dI3nY76wGaru7T/arcgis/rest/services/TILE_DRAINAGE_AREA_subset/FeatureServer

spring: 
  datasource:
    url: jdbc:sqlserver://arcgislocationmapping.database.windows.net:1433;database=Oasis-Poc1-BiDirectional-DB;user=Mpatel101010@arcgislocationmapping;password=Monee101010;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: Mpatel101010@arcgislocationmapping
    password: Monee101010
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none 
      
logging:
  level:
   '[org.springframework.web]': TRACE
  

  
      
    