package com.oasis.poc1.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.oasis.poc1.service.Poc1Service;

import io.swagger.v3.oas.annotations.Hidden;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Tag(name = "OASIS - POC 1", description = "Core Web - ArcGIS Communucation")
@RestController
public class Poc1Controller {
	
	@Autowired
	Poc1Service service;
	
	Logger logger = LoggerFactory.getLogger(Poc1Controller.class);
	
	@Operation(
			summary = "Welcome Message",
			description = "Welcome Message of OASIS - POC 1",
			responses = {
				@ApiResponse(
						responseCode = "200",
						description = "Success",						
						content =@Content (
								mediaType = "String",
								schema=@Schema(
										example = "Hello From Core Web Application, OASIS - POC-1."
										)
								)
						)
			    }				
			)
	@GetMapping("/OASIS/POC1")
	public String welcomeMessage() {
		return "Hello From Core Web Application, OASIS - POC-1.";		
	}
	
	@Hidden
	@GetMapping("/testGetApi")
	public ResponseEntity<?> testExternalGetRestApi(@RequestBody String url){
		ResponseEntity<?> responseEntity=service.testExternalGetRestAPIUsingRestTemmplate(url);
		return responseEntity;		
	}
	/*
	@Operation(
			summary = "Get Token from ArcGIS Enterprise",
			description = "Getting Token generated by ArcGIS Enterprise"
			)
	@ApiResponses({
				@ApiResponse(responseCode = "200", content = {@Content(schema= @Schema(implementation = Token.class), mediaType = "application/json")}),
				@ApiResponse(responseCode = "400", content = {@Content(schema= @Schema(implementation = Error.class), mediaType = "application/json")}),
				@ApiResponse(responseCode ="500", content= {@Content(schema=@Schema())})
			})
			*/
			
	@GetMapping("/getTokenAPI")
	public ResponseEntity<?> testTokenApi(){	
		ResponseEntity<?> responseEntity = service.testGenerateTokenApi();			
		return responseEntity;				
	}

	@GetMapping("/getWellQuery")
	public ResponseEntity<?> testPetroleumWellApi(){	
		ResponseEntity<?> responseEntity=service.testPetroleumWellSubsetQuery();		
		return responseEntity;				
	}
	
	@GetMapping("/getTileQuery")
	public ResponseEntity<?> testTileDrainageAreaApi(){	
		ResponseEntity<?> responseEntity=service.testTileDrainageAreaSubsetQuery();		
		return responseEntity;				
	}
}
